### ISSUE TITLE
The rules aren't analyzed correctly

### ISSUE THREAD

**Issue by ghost** [silvaquill/flakes#5]
The rules aren't analyzed correctly because:

- The _linter rules_ are nested inside other _linter rules_:

```yaml
linter:
  rules:
    linter:
      rules:
```

- The `analysis_options` includes the YAML from the `lib` folder, instead of including from the `package`.:

```yaml
include: lib/flakes.yaml
```
